In [81]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import requests
%matplotlib inline

In [82]:
url = "https://github.com/winifredpaul/vanguard-ui-experiment-analysis/blob/main/data/df_final_demo.txt"

response = requests.get(url)

print(response.status_code)

200

In [85]:
df_final_demo = "https://raw.githubusercontent.com/winifredpaul/vanguard-ui-experiment-analysis/main/data/df_final_demo.txt"
df_final_web_data_pt_1 = "https://raw.githubusercontent.com/winifredpaul/vanguard-ui-experiment-analysis/main/data/df_final_web_data_pt_1.zip"
df_final_web_data_pt_2 = "https://raw.githubusercontent.com/winifredpaul/vanguard-ui-experiment-analysis/main/data/df_final_web_data_pt_2.zip"
df_final_experiment_clients = "https://raw.githubusercontent.com/winifredpaul/vanguard-ui-experiment-analysis/main/data/df_final_experiment_clients.txt"
clients_demo_df = pd.read_csv(df_final_demo)
web_data_pt1_df = pd.read_csv(df_final_web_data_pt_1, compression="zip")
web_data_pt2_df = pd.read_csv(df_final_web_data_pt_2, compression="zip")
experiment_clients_df = pd.read_csv(df_final_experiment_clients)

In [86]:
clients_demo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70609 entries, 0 to 70608
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   client_id         70609 non-null  int64
 1   clnt_tenure_yr    70595 non-null  float64
 2   clnt_tenure_mnth  70595 non-null  float64
 3   clnt_age          70594 non-null  float64
 4   gendr             70595 non-null  object
 5   num_accts         70595 non-null  float64
 6   bal               70595 non-null  float64
 7   calls_6_mnth      70595 non-null  float64
 8   logons_6_mnth     70595 non-null  float64
dtypes: float64(7), int64(1), object(1)
memory usage: 4.8+ MB

In [4]:
df_final_demo["gendr"].unique()

array(['U', 'M', 'F', nan, 'X'], dtype=object)

In [5]:
df_final_demo["gendr"].value_counts()

gendr
U    24122
M    23724
F    22746
X        3
Name: count, dtype: int64

In [6]:
df_final_demo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70609 entries, 0 to 70608
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   client_id         70609 non-null  int64
 1   clnt_tenure_yr    70595 non-null  float64
 2   clnt_tenure_mnth  70595 non-null  float64
 3   clnt_age          70594 non-null  float64
 4   gendr             70595 non-null  object
 5   num_accts         70595 non-null  float64
 6   bal               70595 non-null  float64
 7   calls_6_mnth      70595 non-null  float64
 8   logons_6_mnth     70595 non-null  float64
dtypes: float64(7), int64(1), object(1)
memory usage: 4.8+ MB

In [7]:
df_final_demo.isnull().sum()

client_id            0
clnt_tenure_yr      14
clnt_tenure_mnth    14
clnt_age            15
gendr               14
num_accts           14
bal                 14
calls_6_mnth        14
logons_6_mnth       14
dtype: int64

In [8]:
df_final_demo.duplicated().sum()

np.int64(0)

In [9]:
df_final_demo.describe()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,num_accts,bal,calls_6_mnth,logons_6_mnth
count,7.060900e+04,70595.000000,70595.000000,70594.000000,70595.000000,7.059500e+04,70595.000000,70595.000000
mean,5.004992e+06,12.052950,150.659367,46.442240,2.255528,1.474452e+05,3.382478,5.566740
std,2.877278e+06,6.871819,82.089854,15.591273,0.534997,3.015087e+05,2.236580,2.353286
min,1.690000e+02,2.000000,33.000000,13.500000,1.000000,1.378942e+04,0.000000,1.000000
25%,2.519329e+06,6.000000,82.000000,32.500000,2.000000,3.734683e+04,1.000000,4.000000
50%,5.016978e+06,11.000000,136.000000,47.000000,2.000000,6.333290e+04,3.000000,5.000000
75%,7.483085e+06,16.000000,192.000000,59.000000,2.000000,1.375449e+05,6.000000,7.000000
max,9.999839e+06,62.000000,749.000000,96.000000,8.000000,1.632004e+07,7.000000,9.000000

In [10]:
df_final_demo[df_final_demo.isnull().any(axis=1)]

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
4164,7402828,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8316,355337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8677,8412164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9583,4666211,8.0,106.0,NaN,F,2.0,42550.55,4.0,7.0
13444,2222915,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18066,4876926,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25961,5277910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28432,7616759,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35323,8191345,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43518,1227228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46076,8611797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47189,5144725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49846,1037867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63701,1618749,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66219,6021001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df_final_web_data_pt_1.head()

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04

In [12]:
df_final_web_data_pt_1["process_step"].unique()

array(['step_3', 'step_2', 'step_1', 'start', 'confirm'], dtype=object)

In [13]:
df_final_web_data_pt_2.head()

,client_id,visitor_id,visit_id,process_step,date_time
0,763412,601952081_10457207388,397475557_40440946728_419634,confirm,2017-06-06 08:56:00
1,6019349,442094451_91531546617,154620534_35331068705_522317,confirm,2017-06-01 11:59:27
2,6019349,442094451_91531546617,154620534_35331068705_522317,step_3,2017-06-01 11:58:48
3,6019349,442094451_91531546617,154620534_35331068705_522317,step_2,2017-06-01 11:58:08
4,6019349,442094451_91531546617,154620534_35331068705_522317,step_1,2017-06-01 11:57:58

In [14]:
df_final_web_data_pt_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 343141 entries, 0 to 343140
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   client_id     343141 non-null  int64
 1   visitor_id    343141 non-null  object
 2   visit_id      343141 non-null  object
 3   process_step  343141 non-null  object
 4   date_time     343141 non-null  object
dtypes: int64(1), object(4)
memory usage: 13.1+ MB

In [15]:
df_final_web_data_pt_1.head(10)

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04
5,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:17:15
6,9988021,580560515_7732621733,781255054_21935453173_531117,step_1,2017-04-17 15:17:01
7,9988021,580560515_7732621733,781255054_21935453173_531117,start,2017-04-17 15:16:22
8,8320017,39393514_33118319366,960651974_70596002104_312201,confirm,2017-04-05 13:10:05
9,8320017,39393514_33118319366,960651974_70596002104_312201,step_3,2017-04-05 13:09:43

In [16]:
df_final_web_data_pt_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 412264 entries, 0 to 412263
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   client_id     412264 non-null  int64
 1   visitor_id    412264 non-null  object
 2   visit_id      412264 non-null  object
 3   process_step  412264 non-null  object
 4   date_time     412264 non-null  object
dtypes: int64(1), object(4)
memory usage: 15.7+ MB

In [17]:
df_final_experiment_clients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70609 entries, 0 to 70608
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   client_id  70609 non-null  int64
 1   Variation  50500 non-null  object
dtypes: int64(1), object(1)
memory usage: 1.1+ MB

In [18]:
df_final_experiment_clients.isnull().sum()

client_id        0
Variation    20109
dtype: int64

In [19]:
df_final_experiment_clients["Variation"].unique()

array(['Test', 'Control', nan], dtype=object)

In [20]:
df_final_experiment_clients["client_id"].duplicated().sum()

np.int64(0)

In [21]:
df_final_experiment_clients.duplicated().sum()

np.int64(0)

## Merging Demo file with client  part of experiment file

In [22]:
# STEP 1: Check how many unique clients are in dataset 1
dataset_1_clients = df_final_demo["client_id"].nunique()

# STEP 2: Check how many unique clients are in dataset 4
dataset_4_clients = df_final_experiment_clients["client_id"].nunique()

# STEP 3: Find clients that appear in both datasets
overlapping_clients = df_final_demo.merge(df_final_experiment_clients,on="client_id",how="inner")

# STEP 4: Count the unique overlapping clients
overlap_count = overlapping_clients["client_id"].nunique()

# STEP 5: Display the results
print("Unique clients in dataset 1:", dataset_1_clients)
print("Unique clients in dataset 4:", dataset_4_clients)
print("Clients appearing in both datasets:", overlap_count)

# STEP 6: Preview the overlapping clients and their experiment variation
overlapping_clients.head(10)

Unique clients in dataset 1: 70609
Unique clients in dataset 4: 70609
Clients appearing in both datasets: 70609

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,Variation
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0,Test
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0,Control
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0,Test
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0,Test
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0,Control
5,3727881,5.0,71.0,30.5,U,2.0,23915.60,0.0,3.0,Control
6,272934,5.0,66.0,58.5,U,2.0,27021.42,2.0,5.0,Control
7,388801,30.0,361.0,57.5,M,5.0,522498.72,1.0,4.0,Test
8,285619,30.0,369.0,67.5,M,2.0,299388.72,3.0,6.0,Control
9,8198645,15.0,189.0,54.5,F,2.0,382303.83,6.0,9.0,Test

In [28]:
# STEP 1: Count unique clients in dataset 1
dataset_1_clients = df_final_demo["client_id"].nunique()

# STEP 2: Count unique clients assigned to the experiment (exclude NaN)
dataset_4_clients = (
    df_final_experiment_clients
    .loc[df_final_experiment_clients["Variation"].notna(), "client_id"]
    .nunique()
)

# STEP 3: Find clients appearing in both datasets
overlapping_clients = df_final_demo.merge(
    df_final_experiment_clients,
    on="client_id",
    how="inner"
)

# STEP 4: Count unique overlapping clients who participated in the experiment
overlap_count = (
    overlapping_clients
    .loc[overlapping_clients["Variation"].notna(), "client_id"]
    .nunique()
)

# STEP 5: Display the results
print("Unique clients in dataset 1:", dataset_1_clients)
print("Unique experiment clients:", dataset_4_clients)
print("Clients appearing in both datasets:", overlap_count)

# STEP 6: Preview the overlapping clients
overlapping_clients.head(10)

Unique clients in dataset 1: 70609
Unique experiment clients: 50500
Clients appearing in both datasets: 50500

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,Variation
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0,Test
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0,Control
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0,Test
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0,Test
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0,Control
5,3727881,5.0,71.0,30.5,U,2.0,23915.60,0.0,3.0,Control
6,272934,5.0,66.0,58.5,U,2.0,27021.42,2.0,5.0,Control
7,388801,30.0,361.0,57.5,M,5.0,522498.72,1.0,4.0,Test
8,285619,30.0,369.0,67.5,M,2.0,299388.72,3.0,6.0,Control
9,8198645,15.0,189.0,54.5,F,2.0,382303.83,6.0,9.0,Test

In [25]:
# Merge Variation column into the demo dataset
df_final_demo_exp = df_final_demo.merge(
    df_final_experiment_clients[["client_id", "Variation"]],
    on="client_id",
    how="left"
)

# Create a new flag indicating whether the client was part of the experiment
df_final_demo_exp["part_of_experiment"] = df_final_demo_exp["Variation"].notna().map({
    True: "Yes",
    False: "No"
})

# Preview
df_final_demo_exp.head()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,Variation,part_of_experiment
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0,Test,Yes
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0,Control,Yes
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0,Test,Yes
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0,Test,Yes
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0,Control,Yes

In [30]:
df_final_demo_exp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70609 entries, 0 to 70608
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   client_id           70609 non-null  int64
 1   clnt_tenure_yr      70595 non-null  float64
 2   clnt_tenure_mnth    70595 non-null  float64
 3   clnt_age            70594 non-null  float64
 4   gendr               70595 non-null  object
 5   num_accts           70595 non-null  float64
 6   bal                 70595 non-null  float64
 7   calls_6_mnth        70595 non-null  float64
 8   logons_6_mnth       70595 non-null  float64
 9   Variation           50500 non-null  object
 10  part_of_experiment  70609 non-null  object
dtypes: float64(7), int64(1), object(3)
memory usage: 5.9+ MB

In [34]:
df_final_demo_exp["Variation"].value_counts(dropna = False)

Variation
Test       26968
Control    23532
NaN        20109
Name: count, dtype: int64

In [31]:
# Check gender distribution by variation
gender_by_variation = pd.crosstab(
    df_final_demo_exp["Variation"],
    df_final_demo_exp["gendr"]
)

print(gender_by_variation)

gendr         F     M     U  X
Variation
Control    7543  7970  8014  0
Test       8716  8977  9266  2

In [36]:
# Create final experiment dataframe with only Test and Control clients
df_experiment = df_final_demo_exp[
    df_final_demo_exp["Variation"].isin(["Test", "Control"])
].copy()

# Optional: remove the participation flag because all rows are experiment clients
df_experiment = df_experiment.drop(columns=["part_of_experiment"])

# Check the result
df_experiment.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50500 entries, 0 to 50499
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   client_id         50500 non-null  int64
 1   clnt_tenure_yr    50488 non-null  float64
 2   clnt_tenure_mnth  50488 non-null  float64
 3   clnt_age          50487 non-null  float64
 4   gendr             50488 non-null  object
 5   num_accts         50488 non-null  float64
 6   bal               50488 non-null  float64
 7   calls_6_mnth      50488 non-null  float64
 8   logons_6_mnth     50488 non-null  float64
 9   Variation         50500 non-null  object
dtypes: float64(7), int64(1), object(2)
memory usage: 4.2+ MB

In [37]:
df_experiment.head()

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,Variation
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0,Test
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0,Control
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0,Test
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0,Test
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0,Control

In [38]:
df_experiment["Variation"].value_counts(dropna = False)

Variation
Test       26968
Control    23532
Name: count, dtype: int64

In [39]:
missing_rows = df_experiment[df_experiment.isnull().any(axis=1)]

missing_rows

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth,Variation
4164,7402828,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Control
8316,355337,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Control
8677,8412164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Test
9583,4666211,8.0,106.0,NaN,F,2.0,42550.55,4.0,7.0,Control
13444,2222915,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Test
18066,4876926,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Test
25961,5277910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Test
28432,7616759,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Control
35323,8191345,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Control
43518,1227228,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Test
46076,8611797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Control
47189,5144725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Test
49846,1037867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Test

In [40]:
# Drop rows with any missing values
df_experiment_clean = df_experiment.dropna()

# Check the result
df_experiment_clean.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50487 entries, 0 to 50499
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   client_id         50487 non-null  int64
 1   clnt_tenure_yr    50487 non-null  float64
 2   clnt_tenure_mnth  50487 non-null  float64
 3   clnt_age          50487 non-null  float64
 4   gendr             50487 non-null  object
 5   num_accts         50487 non-null  float64
 6   bal               50487 non-null  float64
 7   calls_6_mnth      50487 non-null  float64
 8   logons_6_mnth     50487 non-null  float64
 9   Variation         50487 non-null  object
dtypes: float64(7), int64(1), object(2)
memory usage: 4.2+ MB

### Identifying Clients Participating in the A/B Experiment

To determine which clients were included in the A/B test, the client demographics dataset (`df_final_demo`) was merged with the experiment roster (`df_final_experiment_clients`) using the `client_id` field.

The `Variation` column from the experiment dataset was added to the demographics dataset, indicating whether each client belonged to the **Test** group, **Control** group, or was **not part of the experiment** (`NaN`).

A new boolean column, `part_of_experiment`, was then created:

- **True** → Client participated in the A/B experiment (assigned to either the Test or Control group).
- **False** → Client was not included in the experiment.

This flag simplifies filtering the dataset for subsequent analyses, such as calculating performance metrics, comparing completion rates, and conducting hypothesis testing using only the experimental population.

## Merging web dat 2 with web data 2

In [41]:
# Combine the two web datasets
df_final_web_data = pd.concat(
    [df_final_web_data_pt_1, df_final_web_data_pt_2],
    ignore_index=True
)

# Check the result
df_final_web_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 755405 entries, 0 to 755404
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   client_id     755405 non-null  int64
 1   visitor_id    755405 non-null  object
 2   visit_id      755405 non-null  object
 3   process_step  755405 non-null  object
 4   date_time     755405 non-null  object
dtypes: int64(1), object(4)
memory usage: 28.8+ MB

In [42]:
# Check duplicate rows
df_final_web_data.duplicated().sum()

np.int64(10764)

In [43]:
df_final_web_data["process_step"].unique()

array(['step_3', 'step_2', 'step_1', 'start', 'confirm'], dtype=object)

In [44]:
#Convert date_time to datetime
df_final_web_data["date_time"] = pd.to_datetime(
    df_final_web_data["date_time"]
)

In [45]:
df_final_web_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 755405 entries, 0 to 755404
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   client_id     755405 non-null  int64
 1   visitor_id    755405 non-null  object
 2   visit_id      755405 non-null  object
 3   process_step  755405 non-null  object
 4   date_time     755405 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 28.8+ MB

In [46]:
# Sort by time
df_final_web_data = df_final_web_data.sort_values("date_time")

# Get the latest record for each client
client_last_step = (
    df_final_web_data
    .groupby("client_id")
    .last()
    .reset_index()
)

client_last_step[["client_id", "process_step"]].head()

   client_id process_step
0        169      confirm
1        336        start
2        546      confirm
3        555      confirm
4        647      confirm

In [47]:
# Sort by time
df_final_web_data = df_final_web_data.sort_values("date_time")

# Get the latest record for each client
client_last_step = (
    df_final_web_data
    .groupby("client_id")
    .last()
    .reset_index()
)

# Add the Variation (Test/Control/NaN) for each client
client_last_step = client_last_step.merge(
    df_final_experiment_clients[["client_id", "Variation"]],
    on="client_id",
    how="left"
)

# Display the relevant columns
client_last_step[["client_id", "process_step", "Variation",]].head(20)

    client_id process_step Variation
0         169      confirm       NaN
1         336        start       NaN
2         546      confirm       NaN
3         555      confirm      Test
4         647      confirm      Test
5         722      confirm       NaN
6         786      confirm       NaN
7         805       step_1       NaN
8         832      confirm       NaN
9         934        start      Test
10       1028       step_1   Control
11       1039      confirm       NaN
12       1104        start   Control
13       1186       step_2   Control
14       1195      confirm   Control
15       1197      confirm   Control
16       1281      confirm       NaN
17       1336      confirm      Test
18       1346       step_3      Test
19       1357      confirm       NaN

In [48]:
client_id = 934

(
    df_final_web_data[df_final_web_data["client_id"] == client_id]
    .sort_values("date_time")
)

,client_id,visitor_id,visit_id,process_step,date_time
62623,934,810392784_45004760546,7076463_57954418406_971348,start,2017-04-18 02:36:30
62622,934,810392784_45004760546,7076463_57954418406_971348,start,2017-04-18 02:37:02
62621,934,810392784_45004760546,7076463_57954418406_971348,start,2017-04-18 02:38:24
62620,934,810392784_45004760546,7076463_57954418406_971348,start,2017-04-18 02:38:52

## Latest Client Process Step and Experiment Assignment

This analysis consolidates the web activity data to a client-level view by identifying the most recent interaction recorded for each client. The web activity dataset is first sorted chronologically, ensuring that the latest event for each client appears last in their activity history. The data is then grouped by `client_id`, and the final record for each client is retained, representing the furthest process step reached by that client.

The resulting dataset is enriched with experiment information by joining it with the experiment client dataset on `client_id`. This adds the `Variation` field, allowing each client to be classified into the corresponding experimental group (e.g., Test or Control).

As a validation step, individual client histories can be inspected by filtering the web activity dataset for a specific `client_id` and sorting the records by timestamp. This confirms that the process step retained in the final client-level dataset corresponds to the client's last recorded activity.

In [53]:
# Convert the timestamp column to datetime

df_final_web_data["date_time"] = pd.to_datetime(df_final_web_data["date_time"])

# Check the observed date range

print("First activity:", df_final_web_data["date_time"].min())
print("Last activity:", df_final_web_data["date_time"].max())

# Define the experiment period

experiment_start = pd.Timestamp("2017-03-15")
experiment_end = pd.Timestamp("2017-06-21")

# Identify activity outside the experiment period

outside_experiment = df_final_web_data[(df_final_web_data["date_time"] < experiment_start) |(df_final_web_data["date_time"] > experiment_end)]

print(f"\nActivities outside the experiment period: {len(outside_experiment)}")

display(outside_experiment.tail())

First activity: 2017-03-15 00:03:03
Last activity: 2017-06-20 23:59:57

Activities outside the experiment period: 0

Empty DataFrame
Columns: [client_id, visitor_id, visit_id, process_step, date_time]
Index: []